// js/config.js
export const TMDB_KEY = '2dca580c2a14b55200e784d157207b4d';
export const TMDB_IMG = 'https://image.tmdb.org/t/p/w500';

// FreeToGame (games database, analogue of TMDB for video games): no signup, no key needed.
// https://www.freetogame.com/api-doc
export const FREETOGAME_API = 'https://www.freetogame.com/api';
// Routed through a CORS proxy that allows github.io origins on its free tier, as a
// safety net in case FreeToGame's own CORS support is inconsistent.
export const CORS_PROXY = 'https://corsproxy.io/?url=';

export const PACK_TYPES = ['movie', 'tv', 'game'];
export const RARS = ['common', 'gold', 'rainbow', 'unique', 'diamond'];
export const PACK_W = [79, 20, 1, 0, 0];
export const LOT_W = [60, 25, 10, 5, 0];
export const SELL_V = { common: 5, gold: 25, rainbow: 200, unique: 300, diamond: 150 };
export const XP_R = { common: 20, gold: 100, rainbow: 1000, unique: 1000, diamond: 0 };
export const BADGE_XP = [50, 150, 400, 1000, 2500];
export const CIRC = 2 * Math.PI * 27;
export const RAR_COLOR = { common: '#aaa', gold: '#fbbf24', rainbow: '#f87171', unique: '#ff4444', diamond: '#60a5fa' };

// Rarity is shown by color, but also by a distinct icon + border style so it reads
// without relying on color perception alone.
export const RAR_ICON = { common: null, gold: 'fa-star', rainbow: 'fa-water', unique: 'fa-award', diamond: 'fa-gem' };
export const RAR_BORDER = { common: 'solid', gold: 'solid', rainbow: 'dashed', unique: 'double', diamond: 'solid' };

export const AVATARS = ['🎬', '🍿', '🎭', '👾', '🦊', '🐺', '🔮', '🌟', '🐉', '🃏'];

export const LANGS = {
  ru: {
    open: 'Открыть', inv: 'Коллекция', shop: 'Магазин', info: 'Прогресс', sett: 'Настройки',
    hint: 'Нажми чтобы открыть', close: 'Закрыть', sell: 'Продать', fav: 'В избранное', unfav: 'Убрать',
    spin: 'Вращать', stop: 'Стоп', newest: 'Новые', all: 'Все', common: 'Обычные', gold: 'Золотые',
    rainbow: 'Радужные', unique: 'Уникальные', diamond: 'Алмазные', faved: 'Избранные',
    rn: { common: 'Обычная', gold: 'Золотая', rainbow: 'Радужная', unique: 'Уникальная', diamond: 'Алмазная' },
    coins: 'монет', shopRef: 'Обновление через', free: 'Бесплатно', buy: 'Купить', lotOf: 'Лот', cards: 'карточек',
    lvlTitle: 'Уровень игрока', questHdr: 'Ежедневные задания', dTitle: '💎 Прогресс до алмазной карточки',
    dRight: 'Алмазная карта', dLabel: n => `${n} из 3`, claim: 'Получить алмазную', ddCollect: 'Забрать в коллекцию', ddTitle: '✦ АЛМАЗНАЯ КАРТОЧКА ✦', badgesHdr: 'Значки',
    noCards: 'Нет карточек', lvlUp: '🎉 УРОВЕНЬ ПОВЫШЕН!', streakTitle: 'Стрик входов', streakSub: 'дней подряд',
    sellConfirm: (t, p) => `Продать "${t}" за ${p} монет?`, settTitle: '⚙️ Настройки',
    newCards: 'Новые карточки!', ok: 'OK', diff: { easy: '🌱 Лёгкое', medium: '⚡ Среднее', hard: '🔥 Сложное' },
    noCoin: 'Недостаточно монет', badgeLocked: 'Не открыт', badgeMax: 'Максимум!', next: 'Далее',
    finish: 'Поехали!', prev: '←', retut: '▶ Начать', changelog: '📋 Журнал обновлений',
    tooltipsLbl: 'Подсказки названий', tooltipsSub: 'Показывать имя фильма при наведении',
    selectMode: 'Выбрать', selected: n => `Выбрано: ${n}`,
    addToFav: 'В избранное', removeFromFav: 'Убрать из избранного', deleteSel: 'Удалить',
    addToCol: 'В коллекцию', cancelSel: 'Отмена', selAll: 'Все',
    deleteConfirm: n => `Удалить ${n} карточек? Действие необратимо.`,
    sellSel: 'Продать', sellSelConfirm: (n, v) => `Продать ${n} карт. за ${v} монет?`, sellSelDone: v => `Продано за ${v} монет`,
    cardIdLbl: 'Карточка', autoTilt: 'Авто-наклон', spinHint: 'Вращать',
    colTitle: 'Коллекции', colNew: 'Новая коллекция', colNamePh: 'Название коллекции...',
    colCreate: 'Создать', colCost: n => `Стоимость: ${n} монет`, colMax: 'Достигнут лимит коллекций (4)',
    colNoCoin: 'Недостаточно монет для создания коллекции', colDelete: 'Удалить коллекцию',
    colDeleteConfirm: 'Удалить коллекцию? Карточки вернутся в «Все».', colRename: 'Переименовать',
    colAll: 'Все', colChoose: 'Выберите коллекцию', colCreateNew: '+ Новая коллекция',
    colMovedTo: n => `Перемещено в «${n}»`, vis: 'Визуал', bgLbl: 'Оттенок фона',
    rotateBtn: 'Повернуть', selectBtn: 'Выбрать карты', colDeleted: 'Коллекция удалена',
    colNameSaved: 'Название сохранено', langLbl: 'Язык', avatarLbl: 'Иконка профиля', packMovie: 'Фильмы', packTv: 'Сериалы', packGame: 'Игры', packPickTitle: 'Что открываем?', catalogBtn: 'Каталог', catalogTitle: 'Каталог коллекции', catalogOwned: (n, t) => `Собрано ${n} из ${t}`, catalogUnknown: 'Ещё не встречалось', genreLbl: 'Жанр', releasedLbl: 'Год выхода', ratingLbl: 'Рейтинг', catalogHint: 'Введи название карты, чтобы найти её', catalogNoMatch: 'Ничего не найдено', catalogUnowned: 'Ещё нет в коллекции'
  },
  en: {
    open: 'Open', inv: 'Collection', shop: 'Shop', info: 'Progress', sett: 'Settings',
    hint: 'Tap to open', close: 'Close', sell: 'Sell', fav: 'Favourite', unfav: 'Unfavourite',
    spin: 'Spin', stop: 'Stop', newest: 'New', all: 'All', common: 'Common', gold: 'Gold',
    rainbow: 'Rainbow', unique: 'Unique', diamond: 'Diamond', faved: 'Favourites',
    rn: { common: 'Common', gold: 'Gold', rainbow: 'Rainbow', unique: 'Unique', diamond: 'Diamond' },
    coins: 'coins', shopRef: 'Resets in', free: 'Free', buy: 'Buy', lotOf: 'Lot', cards: 'cards',
    lvlTitle: 'Player Level', questHdr: 'Daily Quests', dTitle: '💎 Progress to Diamond Card',
    dRight: 'Diamond Card', dLabel: n => `${n} of 3`, claim: 'Claim Diamond Card', ddCollect: 'Add to collection', ddTitle: '✦ DIAMOND CARD ✦', badgesHdr: 'Badges',
    noCards: 'No cards', lvlUp: '🎉 LEVEL UP!', streakTitle: 'Daily Streak', streakSub: 'days in a row',
    sellConfirm: (t, p) => `Sell "${t}" for ${p} coins?`, settTitle: '⚙️ Settings',
    newCards: 'New Cards!', ok: 'OK', diff: { easy: '🌱 Easy', medium: '⚡ Medium', hard: '🔥 Hard' },
    noCoin: 'Not enough coins', badgeLocked: 'Not unlocked', badgeMax: 'Max level!', next: 'Next',
    finish: "Let's go!", prev: '←', retut: '▶ Start', changelog: '📋 Changelog',
    tooltipsLbl: 'Title tooltips', tooltipsSub: 'Show movie name on hover',
    selectMode: 'Select', selected: n => `Selected: ${n}`,
    addToFav: 'Favourite', removeFromFav: 'Unfavourite', deleteSel: 'Delete',
    addToCol: 'Add to collection', cancelSel: 'Cancel', selAll: 'All',
    deleteConfirm: n => `Delete ${n} cards? This cannot be undone.`,
    sellSel: 'Sell', sellSelConfirm: (n, v) => `Sell ${n} cards for ${v} coins?`, sellSelDone: v => `Sold for ${v} coins`,
    cardIdLbl: 'Card', autoTilt: 'Auto-tilt', spinHint: 'Spin',
    colTitle: 'Collections', colNew: 'New collection', colNamePh: 'Collection name...',
    colCreate: 'Create', colCost: n => `Cost: ${n} coins`, colMax: 'Collection limit reached (4)',
    colNoCoin: 'Not enough coins to create a collection', colDelete: 'Delete collection',
    colDeleteConfirm: 'Delete this collection? Cards will return to "All".', colRename: 'Rename',
    colAll: 'All', colChoose: 'Choose a collection', colCreateNew: '+ New collection',
    colMovedTo: n => `Moved to "${n}"`, vis: 'Visual', bgLbl: 'Background tint',
    rotateBtn: 'Flip', selectBtn: 'Select cards', colDeleted: 'Collection deleted',
    colNameSaved: 'Name saved', langLbl: 'Language', avatarLbl: 'Profile icon', packMovie: 'Movies', packTv: 'TV Shows', packGame: 'Games', packPickTitle: 'What to open?', catalogBtn: 'Catalog', catalogTitle: 'Collection catalog', catalogOwned: (n, t) => `Collected ${n} of ${t}`, catalogUnknown: 'Not seen yet', genreLbl: 'Genre', releasedLbl: 'Release year', ratingLbl: 'Rating', catalogHint: 'Type a card name to find it', catalogNoMatch: 'No matches found', catalogUnowned: 'Not in your collection yet'
  },
  es: {
    open: 'Abrir', inv: 'Colección', shop: 'Tienda', info: 'Progreso', sett: 'Ajustes',
    hint: 'Toca para abrir', close: 'Cerrar', sell: 'Vender', fav: 'Favorito', unfav: 'Quitar',
    spin: 'Girar', stop: 'Parar', newest: 'Nuevas', all: 'Todo', common: 'Comunes', gold: 'Doradas',
    rainbow: 'Arcoíris', unique: 'Únicas', diamond: 'Diamante', faved: 'Favoritos',
    rn: { common: 'Común', gold: 'Dorada', rainbow: 'Arcoíris', unique: 'Única', diamond: 'Diamante' },
    coins: 'monedas', shopRef: 'Renueva en', free: 'Gratis', buy: 'Comprar', lotOf: 'Lote', cards: 'cartas',
    lvlTitle: 'Nivel del jugador', questHdr: 'Misiones diarias', dTitle: '💎 Progreso a carta Diamante',
    dRight: 'Carta Diamante', dLabel: n => `${n} de 3`, claim: 'Obtener Diamante', ddCollect: 'Añadir a la colección', ddTitle: '✦ CARTA DIAMANTE ✦', badgesHdr: 'Insignias',
    noCards: 'Sin cartas', lvlUp: '🎉 ¡SUBISTE DE NIVEL!', streakTitle: 'Racha diaria', streakSub: 'días seguidos',
    sellConfirm: (t, p) => `¿Vender "${t}" por ${p} monedas?`, settTitle: '⚙️ Ajustes',
    newCards: '¡Nuevas cartas!', ok: 'OK', diff: { easy: '🌱 Fácil', medium: '⚡ Medio', hard: '🔥 Difícil' },
    noCoin: 'Monedas insuficientes', badgeLocked: 'No desbloqueado', badgeMax: '¡Nivel máximo!', next: 'Siguiente',
    finish: '¡Empezar!', prev: '←', retut: '▶ Empezar', changelog: '📋 Novedades',
    tooltipsLbl: 'Sugerencias de título', tooltipsSub: 'Mostrar nombre al pasar el cursor',
    selectMode: 'Seleccionar', selected: n => `Seleccionadas: ${n}`,
    addToFav: 'Favorito', removeFromFav: 'Quitar de favoritos', deleteSel: 'Eliminar',
    addToCol: 'Añadir a colección', cancelSel: 'Cancelar', selAll: 'Todo',
    deleteConfirm: n => `¿Eliminar ${n} cartas? Esta acción no se puede deshacer.`,
    sellSel: 'Vender', sellSelConfirm: (n, v) => `¿Vender ${n} cartas por ${v} monedas?`, sellSelDone: v => `Vendido por ${v} monedas`,
    cardIdLbl: 'Carta', autoTilt: 'Auto-inclinación', spinHint: 'Girar',
    colTitle: 'Colecciones', colNew: 'Nueva colección', colNamePh: 'Nombre de la colección...',
    colCreate: 'Crear', colCost: n => `Costo: ${n} monedas`, colMax: 'Límite de colecciones alcanzado (4)',
    colNoCoin: 'Monedas insuficientes para crear una colección', colDelete: 'Eliminar colección',
    colDeleteConfirm: '¿Eliminar esta colección? Las cartas volverán a "Todo".', colRename: 'Renombrar',
    colAll: 'Todo', colChoose: 'Elige una colección', colCreateNew: '+ Nueva colección',
    colMovedTo: n => `Movido a "${n}"`, vis: 'Visual', bgLbl: 'Tono de fondo',
    rotateBtn: 'Girar', selectBtn: 'Seleccionar cartas', colDeleted: 'Colección eliminada',
    colNameSaved: 'Nombre guardado', langLbl: 'Idioma', avatarLbl: 'Icono de perfil', packMovie: 'Películas', packTv: 'Series', packGame: 'Juegos', packPickTitle: '¿Qué abrimos?', catalogBtn: 'Catálogo', catalogTitle: 'Catálogo de colección', catalogOwned: (n, t) => `Coleccionado ${n} de ${t}`, catalogUnknown: 'Aún no visto', genreLbl: 'Género', releasedLbl: 'Año de lanzamiento', ratingLbl: 'Calificación', catalogHint: 'Escribe el nombre de una carta para buscarla', catalogNoMatch: 'Sin resultados', catalogUnowned: 'Aún no está en tu colección'
  },
  de: {
    open: 'Öffnen', inv: 'Sammlung', shop: 'Shop', info: 'Fortschritt', sett: 'Einstellungen',
    hint: 'Tippen zum Öffnen', close: 'Schließen', sell: 'Verkaufen', fav: 'Favorit', unfav: 'Entfernen',
    spin: 'Drehen', stop: 'Stopp', newest: 'Neu', all: 'Alle', common: 'Gewöhnlich', gold: 'Gold',
    rainbow: 'Regenbogen', unique: 'Einzigartig', diamond: 'Diamant', faved: 'Favoriten',
    rn: { common: 'Gewöhnlich', gold: 'Gold', rainbow: 'Regenbogen', unique: 'Einzigartig', diamond: 'Diamant' },
    coins: 'Münzen', shopRef: 'Neuladen in', free: 'Kostenlos', buy: 'Kaufen', lotOf: 'Paket', cards: 'Karten',
    lvlTitle: 'Spielerlevel', questHdr: 'Tagesaufgaben', dTitle: '💎 Fortschritt zur Diamantkarte',
    dRight: 'Diamantkarte', dLabel: n => `${n} von 3`, claim: 'Diamantkarte holen', ddCollect: 'Zur Sammlung hinzufügen', ddTitle: '✦ DIAMANTKARTE ✦', badgesHdr: 'Abzeichen',
    noCards: 'Keine Karten', lvlUp: '🎉 LEVEL AUFGESTIEGEN!', streakTitle: 'Tages-Streak', streakSub: 'Tage in Folge',
    sellConfirm: (t, p) => `"${t}" für ${p} Münzen verkaufen?`, settTitle: '⚙️ Einstellungen',
    newCards: 'Neue Karten!', ok: 'OK', diff: { easy: '🌱 Leicht', medium: '⚡ Mittel', hard: '🔥 Schwer' },
    noCoin: 'Zu wenig Münzen', badgeLocked: 'Nicht freigeschaltet', badgeMax: 'Maximalstufe!', next: 'Weiter',
    finish: "Los geht's!", prev: '←', retut: '▶ Start', changelog: '📋 Updates',
    tooltipsLbl: 'Titel-Tooltips', tooltipsSub: 'Filmname bei Hover anzeigen',
    selectMode: 'Auswählen', selected: n => `Ausgewählt: ${n}`,
    addToFav: 'Favorit', removeFromFav: 'Favorit entfernen', deleteSel: 'Löschen',
    addToCol: 'Zur Sammlung hinzufügen', cancelSel: 'Abbrechen', selAll: 'Alle',
    deleteConfirm: n => `${n} Karten löschen? Dies kann nicht widerrufen werden.`,
    sellSel: 'Verkaufen', sellSelConfirm: (n, v) => `${n} Karten für ${v} Münzen verkaufen?`, sellSelDone: v => `Für ${v} Münzen verkauft`,
    cardIdLbl: 'Karte', autoTilt: 'Auto-Neigung', spinHint: 'Drehen',
    colTitle: 'Sammlungen', colNew: 'Neue Sammlung', colNamePh: 'Sammlungsname...',
    colCreate: 'Erstellen', colCost: n => `Kosten: ${n} Münzen`, colMax: 'Sammlungslimit erreicht (4)',
    colNoCoin: 'Nicht genug Münzen für eine neue Sammlung', colDelete: 'Sammlung löschen',
    colDeleteConfirm: 'Diese Sammlung löschen? Karten kehren zu "Alle" zurück.', colRename: 'Umbenennen',
    colAll: 'Alle', colChoose: 'Sammlung wählen', colCreateNew: '+ Neue Sammlung',
    colMovedTo: n => `Verschoben nach "${n}"`, vis: 'Visuell', bgLbl: 'Hintergrundfarbton',
    rotateBtn: 'Drehen', selectBtn: 'Karten auswählen', colDeleted: 'Sammlung gelöscht',
    colNameSaved: 'Name gespeichert', langLbl: 'Sprache', avatarLbl: 'Profilsymbol', packMovie: 'Filme', packTv: 'Serien', packGame: 'Spiele', packPickTitle: 'Was öffnen wir?', catalogBtn: 'Katalog', catalogTitle: 'Sammlungskatalog', catalogOwned: (n, t) => `${n} von ${t} gesammelt`, catalogUnknown: 'Noch nicht gesehen', genreLbl: 'Genre', releasedLbl: 'Erscheinungsjahr', ratingLbl: 'Bewertung', catalogHint: 'Kartennamen eingeben, um sie zu finden', catalogNoMatch: 'Keine Treffer', catalogUnowned: 'Noch nicht in deiner Sammlung'
  },
  fr: {
    open: 'Ouvrir', inv: 'Collection', shop: 'Boutique', info: 'Progrès', sett: 'Paramètres',
    hint: 'Appuyer pour ouvrir', close: 'Fermer', sell: 'Vendre', fav: 'Favori', unfav: 'Retirer',
    spin: 'Tourner', stop: 'Arrêter', newest: 'Nouveaux', all: 'Tous', common: 'Commun', gold: 'Or',
    rainbow: 'Arc-en-ciel', unique: 'Unique', diamond: 'Diamant', faved: 'Favoris',
    rn: { common: 'Commun', gold: 'Or', rainbow: 'Arc-en-ciel', unique: 'Unique', diamond: 'Diamant' },
    coins: 'pièces', shopRef: 'Réinitialise dans', free: 'Gratuit', buy: 'Acheter', lotOf: 'Lot', cards: 'cartes',
    lvlTitle: 'Niveau joueur', questHdr: 'Quêtes quotidiennes', dTitle: '💎 Progression carte Diamant',
    dRight: 'Carte Diamant', dLabel: n => `${n} sur 3`, claim: 'Obtenir Diamant', ddCollect: 'Ajouter à la collection', ddTitle: '✦ CARTE DIAMANT ✦', badgesHdr: 'Badges',
    noCards: 'Aucune carte', lvlUp: '🎉 NIVEAU SUPÉRIEUR!', streakTitle: 'Série journalière', streakSub: 'jours consécutifs',
    sellConfirm: (t, p) => `Vendre "${t}" pour ${p} pièces ?`, settTitle: '⚙️ Paramètres',
    newCards: 'Nouvelles cartes !', ok: 'OK', diff: { easy: '🌱 Facile', medium: '⚡ Moyen', hard: '🔥 Difficile' },
    noCoin: 'Pas assez de pièces', badgeLocked: 'Pas débloqué', badgeMax: 'Niveau max !', next: 'Suivant',
    finish: "C'est parti !", prev: '←', retut: '▶ Démarrer', changelog: '📋 Mises à jour',
    tooltipsLbl: 'Infobulles de titre', tooltipsSub: 'Afficher le nom au survol',
    selectMode: 'Sélectionner', selected: n => `Sélectionné : ${n}`,
    addToFav: 'Favori', removeFromFav: 'Retirer des favoris', deleteSel: 'Supprimer',
    addToCol: 'Ajouter à la collection', cancelSel: 'Annuler', selAll: 'Tous',
    deleteConfirm: n => `Supprimer ${n} cartes ? Action irréversible.`,
    sellSel: 'Vendre', sellSelConfirm: (n, v) => `Vendre ${n} cartes pour ${v} pièces ?`, sellSelDone: v => `Vendu pour ${v} pièces`,
    cardIdLbl: 'Carte', autoTilt: 'Inclinaison auto', spinHint: 'Tourner',
    colTitle: 'Collections', colNew: 'Nouvelle collection', colNamePh: 'Nom de la collection...',
    colCreate: 'Créer', colCost: n => `Coût : ${n} pièces`, colMax: 'Limite de collections atteinte (4)',
    colNoCoin: 'Pas assez de pièces pour créer une collection', colDelete: 'Supprimer la collection',
    colDeleteConfirm: 'Supprimer cette collection ? Les cartes reviendront à "Tous".', colRename: 'Renommer',
    colAll: 'Tous', colChoose: 'Choisir une collection', colCreateNew: '+ Nouvelle collection',
    colMovedTo: n => `Déplacé vers "${n}"`, vis: 'Visuel', bgLbl: 'Teinte de fond',
    rotateBtn: 'Retourner', selectBtn: 'Sélectionner des cartes', colDeleted: 'Collection supprimée',
    colNameSaved: 'Nom enregistré', langLbl: 'Langue', avatarLbl: 'Icône de profil', packMovie: 'Films', packTv: 'Séries', packGame: 'Jeux', packPickTitle: 'Que voulez-vous ouvrir ?', catalogBtn: 'Catalogue', catalogTitle: 'Catalogue de collection', catalogOwned: (n, t) => `${n} sur ${t} collectés`, catalogUnknown: 'Pas encore vu', genreLbl: 'Genre', releasedLbl: 'Année de sortie', ratingLbl: 'Note', catalogHint: 'Tapez le nom d\'une carte pour la trouver', catalogNoMatch: 'Aucun résultat', catalogUnowned: 'Pas encore dans votre collection'
  },
  tr: {
    open: 'Aç', inv: 'Koleksiyon', shop: 'Mağaza', info: 'İlerleme', sett: 'Ayarlar',
    hint: 'Açmak için dokun', close: 'Kapat', sell: 'Sat', fav: 'Favorile', unfav: 'Çıkar',
    spin: 'Döndür', stop: 'Dur', newest: 'Yeni', all: 'Hepsi', common: 'Yaygın', gold: 'Altın',
    rainbow: 'Gökkuşağı', unique: 'Eşsiz', diamond: 'Elmas', faved: 'Favoriler',
    rn: { common: 'Yaygın', gold: 'Altın', rainbow: 'Gökkuşağı', unique: 'Eşsiz', diamond: 'Elmas' },
    coins: 'altın', shopRef: 'Yenileme', free: 'Ücretsiz', buy: 'Satın Al', lotOf: 'Paket', cards: 'kart',
    lvlTitle: 'Oyuncu Seviyesi', questHdr: 'Günlük Görevler', dTitle: '💎 Elmas Kart İlerlemesi',
    dRight: 'Elmas Kart', dLabel: n => `${n} / 3`, claim: 'Elmas Kartı Al', ddCollect: 'Koleksiyona ekle', ddTitle: '✦ ELMAS KART ✦', badgesHdr: 'Rozetler',
    noCards: 'Kart yok', lvlUp: '🎉 SEVİYE ATLANDI!', streakTitle: 'Günlük Seri', streakSub: 'gün üst üste',
    sellConfirm: (t, p) => `"${t}" satılsın mı? ${p} altın`, settTitle: '⚙️ Ayarlar',
    newCards: 'Yeni kartlar!', ok: 'Tamam', diff: { easy: '🌱 Kolay', medium: '⚡ Orta', hard: '🔥 Zor' },
    noCoin: 'Yetersiz altın', badgeLocked: 'Kilitli', badgeMax: 'Max seviye!', next: 'Sonraki',
    finish: 'Başlayalım!', prev: '←', retut: '▶ Başlat', changelog: '📋 Güncellemeler',
    tooltipsLbl: 'Başlık ipuçları', tooltipsSub: 'Üzerine gelince film adını göster',
    selectMode: 'Seç', selected: n => `Seçili: ${n}`,
    addToFav: 'Favorile', removeFromFav: 'Favoriden çıkar', deleteSel: 'Sil',
    addToCol: 'Koleksiyona ekle', cancelSel: 'Vazgeç', selAll: 'Hepsi',
    deleteConfirm: n => `${n} kart silinsin mi? Bu işlem geri alınamaz.`,
    sellSel: 'Sat', sellSelConfirm: (n, v) => `${n} kart ${v} altına satılsın mı?`, sellSelDone: v => `${v} altına satıldı`,
    cardIdLbl: 'Kart', autoTilt: 'Otomatik eğim', spinHint: 'Döndür',
    colTitle: 'Koleksiyonlar', colNew: 'Yeni koleksiyon', colNamePh: 'Koleksiyon adı...',
    colCreate: 'Oluştur', colCost: n => `Maliyet: ${n} altın`, colMax: 'Koleksiyon sınırına ulaşıldı (4)',
    colNoCoin: 'Koleksiyon oluşturmak için yetersiz altın', colDelete: 'Koleksiyonu sil',
    colDeleteConfirm: 'Bu koleksiyon silinsin mi? Kartlar "Hepsi"ye dönecek.', colRename: 'Yeniden adlandır',
    colAll: 'Hepsi', colChoose: 'Koleksiyon seç', colCreateNew: '+ Yeni koleksiyon',
    colMovedTo: n => `"${n}" konumuna taşındı`, vis: 'Görsel', bgLbl: 'Arka plan tonu',
    rotateBtn: 'Çevir', selectBtn: 'Kartları seç', colDeleted: 'Koleksiyon silindi',
    colNameSaved: 'İsim kaydedildi', langLbl: 'Dil', avatarLbl: 'Profil simgesi', packMovie: 'Filmler', packTv: 'Diziler', packGame: 'Oyunlar', packPickTitle: 'Ne açalım?', catalogBtn: 'Katalog', catalogTitle: 'Koleksiyon kataloğu', catalogOwned: (n, t) => `${t} üzerinden ${n} toplandı`, catalogUnknown: 'Henüz görülmedi', genreLbl: 'Tür', releasedLbl: 'Çıkış yılı', ratingLbl: 'Puan', catalogHint: 'Bulmak için kart adını yaz', catalogNoMatch: 'Sonuç bulunamadı', catalogUnowned: 'Henüz koleksiyonunda yok'
  },
  ja: {
    open: '開く', inv: 'コレクション', shop: 'ショップ', info: '進捗', sett: '設定',
    hint: 'タップして開く', close: '閉じる', sell: '売る', fav: 'お気に入り', unfav: '外す',
    spin: '回転', stop: '停止', newest: '新しい', all: 'すべて', common: 'コモン', gold: 'ゴールド',
    rainbow: 'レインボー', unique: 'ユニーク', diamond: 'ダイヤモンド', faved: 'お気に入り',
    rn: { common: 'コモン', gold: 'ゴールド', rainbow: 'レインボー', unique: 'ユニーク', diamond: 'ダイヤモンド' },
    coins: 'コイン', shopRef: '更新まで', free: '無料', buy: '買う', lotOf: 'ロット', cards: '枚',
    lvlTitle: 'プレイヤーレベル', questHdr: 'デイリークエスト', dTitle: '💎 ダイヤモンドへの進捗',
    dRight: 'ダイヤモンドカード', dLabel: n => `${n} / 3`, claim: 'ダイヤモンドを獲得', ddCollect: 'コレクションに追加', ddTitle: '✦ ダイヤモンドカード ✦', badgesHdr: 'バッジ',
    noCards: 'カードなし', lvlUp: '🎉 レベルアップ!', streakTitle: 'デイリーストリーク', streakSub: '日連続',
    sellConfirm: (t, p) => `"${t}" を ${p} コインで売る?`, settTitle: '⚙️ 設定',
    newCards: '新しいカード!', ok: 'OK', diff: { easy: '🌱 簡単', medium: '⚡ 普通', hard: '🔥 難しい' },
    noCoin: 'コインが足りない', badgeLocked: '未解放', badgeMax: '最大レベル!', next: '次へ',
    finish: '始めよう!', prev: '←', retut: '▶ 開始', changelog: '📋 変更履歴',
    tooltipsLbl: 'タイトルツールチップ', tooltipsSub: 'ホバー時に映画名を表示',
    selectMode: '選択', selected: n => `選択中: ${n}`,
    addToFav: 'お気に入り', removeFromFav: 'お気に入り解除', deleteSel: '削除',
    addToCol: 'コレクションに追加', cancelSel: 'キャンセル', selAll: 'すべて',
    deleteConfirm: n => `${n}枚を削除しますか？元に戻せません。`,
    sellSel: '売却', sellSelConfirm: (n, v) => `${n}枚を${v}コインで売却しますか？`, sellSelDone: v => `${v}コインで売却しました`,
    cardIdLbl: 'カード', autoTilt: '自動チルト', spinHint: '回転',
    colTitle: 'コレクション', colNew: '新しいコレクション', colNamePh: 'コレクション名...',
    colCreate: '作成', colCost: n => `コスト: ${n} コイン`, colMax: 'コレクション上限に達しました (4)',
    colNoCoin: 'コレクション作成にはコインが不足しています', colDelete: 'コレクションを削除',
    colDeleteConfirm: 'このコレクションを削除しますか？カードは「すべて」に戻ります。', colRename: '名前を変更',
    colAll: 'すべて', colChoose: 'コレクションを選択', colCreateNew: '+ 新しいコレクション',
    colMovedTo: n => `「${n}」に移動しました`, vis: 'ビジュアル', bgLbl: '背景色合い',
    rotateBtn: '反転', selectBtn: 'カードを選択', colDeleted: 'コレクションを削除しました',
    colNameSaved: '名前を保存しました', langLbl: '言語', avatarLbl: 'プロフィールアイコン', packMovie: '映画', packTv: 'ドラマ', packGame: 'ゲーム', packPickTitle: '何を開く？', catalogBtn: 'カタログ', catalogTitle: 'コレクションカタログ', catalogOwned: (n, t) => `${t}件中${n}件収集済み`, catalogUnknown: 'まだ未発見', genreLbl: 'ジャンル', releasedLbl: '発売年', ratingLbl: '評価', catalogHint: 'カード名を入力して検索', catalogNoMatch: '見つかりませんでした', catalogUnowned: 'まだコレクションにありません'
  },
  zh: {
    open: '开包', inv: '收藏', shop: '商店', info: '进度', sett: '设置',
    hint: '点击开包', close: '关闭', sell: '出售', fav: '收藏', unfav: '取消',
    spin: '旋转', stop: '停止', newest: '最新', all: '全部', common: '普通', gold: '黄金',
    rainbow: '彩虹', unique: '独特', diamond: '钻石', faved: '收藏夹',
    rn: { common: '普通', gold: '黄金', rainbow: '彩虹', unique: '独特', diamond: '钻石' },
    coins: '金币', shopRef: '更新倒计时', free: '免费', buy: '购买', lotOf: '批次', cards: '张卡',
    lvlTitle: '玩家等级', questHdr: '每日任务', dTitle: '💎 钻石卡进度',
    dRight: '钻石卡', dLabel: n => `${n} / 3`, claim: '领取钻石卡', ddCollect: '添加到收藏集', ddTitle: '✦ 钻石卡 ✦', badgesHdr: '徽章',
    noCards: '没有卡片', lvlUp: '🎉 升级了!', streakTitle: '每日连签', streakSub: '天连续',
    sellConfirm: (t, p) => `出售 "${t}" 获得 ${p} 金币?`, settTitle: '⚙️ 设置',
    newCards: '新卡片!', ok: '确认', diff: { easy: '🌱 简单', medium: '⚡ 中等', hard: '🔥 困难' },
    noCoin: '金币不足', badgeLocked: '未解锁', badgeMax: '最高等级!', next: '下一步',
    finish: '出发!', prev: '←', retut: '▶ 开始', changelog: '📋 更新日志',
    tooltipsLbl: '标题提示', tooltipsSub: '悬停时显示影片名称',
    selectMode: '选择', selected: n => `已选: ${n}`,
    addToFav: '收藏', removeFromFav: '取消收藏', deleteSel: '删除',
    addToCol: '添加到收藏集', cancelSel: '取消', selAll: '全部',
    deleteConfirm: n => `删除${n}张卡片？此操作无法撤销。`,
    sellSel: '出售', sellSelConfirm: (n, v) => `以${v}金币出售${n}张卡片？`, sellSelDone: v => `已出售，获得${v}金币`,
    cardIdLbl: '卡片', autoTilt: '自动倾斜', spinHint: '旋转',
    colTitle: '收藏集', colNew: '新建收藏集', colNamePh: '收藏集名称...',
    colCreate: '创建', colCost: n => `花费：${n} 金币`, colMax: '已达到收藏集上限 (4)',
    colNoCoin: '金币不足，无法创建收藏集', colDelete: '删除收藏集',
    colDeleteConfirm: '删除该收藏集？卡片将返回"全部"。', colRename: '重命名',
    colAll: '全部', colChoose: '选择收藏集', colCreateNew: '+ 新建收藏集',
    colMovedTo: n => `已移动到"${n}"`, vis: '视觉', bgLbl: '背景色调',
    rotateBtn: '翻转', selectBtn: '选择卡片', colDeleted: '收藏集已删除',
    colNameSaved: '名称已保存', langLbl: '语言', avatarLbl: '头像图标', packMovie: '电影', packTv: '剧集', packGame: '游戏', packPickTitle: '打开什么？', catalogBtn: '图鉴', catalogTitle: '收藏图鉴', catalogOwned: (n, t) => `已收集 ${n}/${t}`, catalogUnknown: '尚未发现', genreLbl: '类型', releasedLbl: '发行年份', ratingLbl: '评分', catalogHint: '输入卡片名称进行搜索', catalogNoMatch: '未找到匹配项', catalogUnowned: '尚未收集'
  },
  ar: {
    open: 'افتح', inv: 'المجموعة', shop: 'المتجر', info: 'التقدم', sett: 'الإعدادات',
    hint: 'انقر للفتح', close: 'إغلاق', sell: 'بيع', fav: 'مفضلة', unfav: 'إزالة',
    spin: 'دوران', stop: 'وقف', newest: 'الجديد', all: 'الكل', common: 'عادي', gold: 'ذهبي',
    rainbow: 'قوس قزح', unique: 'فريد', diamond: 'ألماس', faved: 'المفضلة',
    rn: { common: 'عادي', gold: 'ذهبي', rainbow: 'قوس قزح', unique: 'فريد', diamond: 'ألماس' },
    coins: 'عملات', shopRef: 'التجديد خلال', free: 'مجاني', buy: 'شراء', lotOf: 'صفقة', cards: 'بطاقات',
    lvlTitle: 'مستوى اللاعب', questHdr: 'المهام اليومية', dTitle: '💎 تقدم البطاقة الماسية',
    dRight: 'البطاقة الماسية', dLabel: n => `${n} من 3`, claim: 'احصل على الألماس', ddCollect: 'إضافة إلى المجموعة', ddTitle: '✦ البطاقة الماسية ✦', badgesHdr: 'الشارات',
    noCards: 'لا بطاقات', lvlUp: '🎉 ارتقاء!', streakTitle: 'السلسلة اليومية', streakSub: 'أيام متتالية',
    sellConfirm: (t, p) => `بيع "${t}" مقابل ${p} عملة?`, settTitle: '⚙️ الإعدادات',
    newCards: 'بطاقات جديدة!', ok: 'موافق', diff: { easy: '🌱 سهل', medium: '⚡ متوسط', hard: '🔥 صعب' },
    noCoin: 'عملات غير كافية', badgeLocked: 'مقفل', badgeMax: 'أعلى مستوى!', next: 'التالي',
    finish: 'لنبدأ!', prev: '←', retut: '▶ ابدأ', changelog: '📋 سجل التحديثات',
    tooltipsLbl: 'تلميحات العنوان', tooltipsSub: 'إظهار اسم الفيلم عند التمرير',
    selectMode: 'تحديد', selected: n => `المحدد: ${n}`,
    addToFav: 'تفضيل', removeFromFav: 'إزالة من المفضلة', deleteSel: 'حذف',
    addToCol: 'إضافة إلى المجموعة', cancelSel: 'إلغاء', selAll: 'الكل',
    deleteConfirm: n => `حذف ${n} بطاقات؟ لا يمكن التراجع عن هذا الإجراء.`,
    sellSel: 'بيع', sellSelConfirm: (n, v) => `بيع ${n} بطاقات مقابل ${v} عملة؟`, sellSelDone: v => `تم البيع مقابل ${v} عملة`,
    cardIdLbl: 'بطاقة', autoTilt: 'إميل تلقائي', spinHint: 'دوران',
    colTitle: 'المجموعات', colNew: 'مجموعة جديدة', colNamePh: 'اسم المجموعة...',
    colCreate: 'إنشاء', colCost: n => `التكلفة: ${n} عملة`, colMax: 'تم الوصول إلى الحد الأقصى للمجموعات (4)',
    colNoCoin: 'عملات غير كافية لإنشاء مجموعة', colDelete: 'حذف المجموعة',
    colDeleteConfirm: 'حذف هذه المجموعة؟ ستعود البطاقات إلى "الكل".', colRename: 'إعادة تسمية',
    colAll: 'الكل', colChoose: 'اختر مجموعة', colCreateNew: '+ مجموعة جديدة',
    colMovedTo: n => `تم النقل إلى "${n}"`, vis: 'المظهر', bgLbl: 'درجة لون الخلفية',
    rotateBtn: 'قلب', selectBtn: 'تحديد البطاقات', colDeleted: 'تم حذف المجموعة',
    colNameSaved: 'تم حفظ الاسم', langLbl: 'اللغة', avatarLbl: 'أيقونة الملف الشخصي', packMovie: 'أفلام', packTv: 'مسلسلات', packGame: 'ألعاب', packPickTitle: 'ماذا سنفتح؟', catalogBtn: 'الكتالوج', catalogTitle: 'كتالوج المجموعة', catalogOwned: (n, t) => `تم جمع ${n} من ${t}`, catalogUnknown: 'لم تظهر بعد', genreLbl: 'النوع', releasedLbl: 'سنة الإصدار', ratingLbl: 'التقييم', catalogHint: 'اكتب اسم البطاقة للبحث عنها', catalogNoMatch: 'لا توجد نتائج', catalogUnowned: 'ليست في مجموعتك بعد'
  },
  pt: {
    open: 'Abrir', inv: 'Coleção', shop: 'Loja', info: 'Progresso', sett: 'Configurações',
    hint: 'Toque para abrir', close: 'Fechar', sell: 'Vender', fav: 'Favorito', unfav: 'Remover',
    spin: 'Girar', stop: 'Parar', newest: 'Novos', all: 'Todos', common: 'Comum', gold: 'Ouro',
    rainbow: 'Arco-íris', unique: 'Único', diamond: 'Diamante', faved: 'Favoritos',
    rn: { common: 'Comum', gold: 'Ouro', rainbow: 'Arco-íris', unique: 'Único', diamond: 'Diamante' },
    coins: 'moedas', shopRef: 'Atualiza em', free: 'Grátis', buy: 'Comprar', lotOf: 'Lote', cards: 'cartas',
    lvlTitle: 'Nível do jogador', questHdr: 'Missões diárias', dTitle: '💎 Progresso carta Diamante',
    dRight: 'Carta Diamante', dLabel: n => `${n} de 3`, claim: 'Obter Diamante', ddCollect: 'Adicionar à coleção', ddTitle: '✦ CARTA DIAMANTE ✦', badgesHdr: 'Insígnias',
    noCards: 'Sem cartas', lvlUp: '🎉 SUBIU DE NÍVEL!', streakTitle: 'Sequência diária', streakSub: 'dias seguidos',
    sellConfirm: (t, p) => `Vender "${t}" por ${p} moedas?`, settTitle: '⚙️ Configurações',
    newCards: 'Novas cartas!', ok: 'OK', diff: { easy: '🌱 Fácil', medium: '⚡ Médio', hard: '🔥 Difícil' },
    noCoin: 'Moedas insuficientes', badgeLocked: 'Não desbloqueado', badgeMax: 'Nível máximo!', next: 'Próximo',
    finish: 'Vamos lá!', prev: '←', retut: '▶ Começar', changelog: '📋 Novidades',
    tooltipsLbl: 'Dicas de título', tooltipsSub: 'Mostrar nome do filme ao passar o mouse',
    selectMode: 'Selecionar', selected: n => `Selecionado: ${n}`,
    addToFav: 'Favorito', removeFromFav: 'Remover dos favoritos', deleteSel: 'Excluir',
    addToCol: 'Adicionar à coleção', cancelSel: 'Cancelar', selAll: 'Todos',
    deleteConfirm: n => `Excluir ${n} cartas? Esta ação não pode ser desfeita.`,
    sellSel: 'Vender', sellSelConfirm: (n, v) => `Vender ${n} cartas por ${v} moedas?`, sellSelDone: v => `Vendido por ${v} moedas`,
    cardIdLbl: 'Carta', autoTilt: 'Inclinação automática', spinHint: 'Girar',
    colTitle: 'Coleções', colNew: 'Nova coleção', colNamePh: 'Nome da coleção...',
    colCreate: 'Criar', colCost: n => `Custo: ${n} moedas`, colMax: 'Limite de coleções atingido (4)',
    colNoCoin: 'Moedas insuficientes para criar uma coleção', colDelete: 'Excluir coleção',
    colDeleteConfirm: 'Excluir esta coleção? As cartas voltarão para "Todos".', colRename: 'Renomear',
    colAll: 'Todos', colChoose: 'Escolha uma coleção', colCreateNew: '+ Nova coleção',
    colMovedTo: n => `Movido para "${n}"`, vis: 'Visual', bgLbl: 'Tom de fundo',
    rotateBtn: 'Virar', selectBtn: 'Selecionar cartas', colDeleted: 'Coleção excluída',
    colNameSaved: 'Nome salvo', langLbl: 'Idioma', avatarLbl: 'Ícone de perfil', packMovie: 'Filmes', packTv: 'Séries', packGame: 'Jogos', packPickTitle: 'O que abrir?', catalogBtn: 'Catálogo', catalogTitle: 'Catálogo da coleção', catalogOwned: (n, t) => `${n} de ${t} coletados`, catalogUnknown: 'Ainda não visto', genreLbl: 'Gênero', releasedLbl: 'Ano de lançamento', ratingLbl: 'Avaliação', catalogHint: 'Digite o nome de uma carta para encontrá-la', catalogNoMatch: 'Nenhum resultado', catalogUnowned: 'Ainda não está na sua coleção'
  }
};
